name: Solicitud de Funcionalidad
description: Proponé una nueva funcionalidad o mejora para el sistema
title: "[FEATURE] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🧾 Título  
        Especificá brevemente el objetivo principal de la tarea.  
        Ejemplo: Implementar sistema de préstamos concurrente

  - type: textarea
    id: descripcion
    attributes:
      label: 📝 Descripción
      description: ¿Qué se busca lograr con esta tarea?
      placeholder: Crear el sistema que utilice hilos y el patrón productor-consumidor para procesar solicitudes en tiempo real.
    validations:
      required: true

  - type: textarea
    id: requisitos
    attributes:
      label: ✅ Requisitos
      description: Componentes, clases o funcionalidades a desarrollar.
      placeholder: |
        - Clase Prestamo
        - Uso de BlockingQueue
        - Sistema de notificaciones
    validations:
      required: true

  - type: textarea
    id: criterios
    attributes:
      label: 🎯 Criterios de Aceptación
      description: Condiciones para dar por válida la tarea.
      placeholder: |
        - El sistema debe permitir múltiples préstamos simultáneos
        - Se deben manejar excepciones adecuadamente
    validations:
      required: true

  - type: input
    id: milestone
    attributes:
      label: 📂 Etapa / Milestone
      placeholder: Etapa 3 - Sistema de Préstamos y Reservas

  - type: input
    id: etiquetas
    attributes:
      label: 🏷️ Labels adicionales
      placeholder: concurrency, SOLID, refactor
